# fly.toml app configuration file generated for avhris-backend-new on 2024-09-25T01:19:00+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'avhris-backend-new'
primary_region = 'sin'

[build]

[env]
  TZ = 'Asia/Makassar'
  PORT = '7000'
  CORS_ORIGINS='https://avhris-backoffice.fly.dev,http://localhost:8080,http://127.0.0.1:8080'

[[mounts]]
  source = 'data'
  destination = '/app/public'

[http_service]
  internal_port = 7000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
